name: Pull Requests Linter

on:
  pull_request:
    branches: [main]
    paths:
      - 'README.md'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm test
